### ISSUE TITLE
'yargs' dependency is not specified

### ISSUE THREAD

**Issue by ThomasCrvsr** [paf31/purescript-yargs#4]
In the file `Node/Yargs.js` there is a `require('yargs')`. I assume that it's this [yargs](https://www.npmjs.com/package/yargs) package from NPM.

It isn't specified anywhere, so it isn't installed and my program fails at runtime (or when I want to make a bundle via pulp and browserify) ^^

**Comment by paf31** [comment]
Yes, it needs to be installed using `npm`. Maybe I should switch to `npm` for Travis builds too.
